package oracle

import (
	"reflect"
	"testing"

	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
)

func TestDataTypeOfFullMatrix(t *testing.T) {
	d11 := newTestDialector("11.2.0.2.0", 1024)
	d12 := newTestDialector("12.1.0.2.0", 1024) // 不设 MaxStringSize，保持零值 Unknown 态（未探测）
	d19 := newTestDialector("19.0.0.0.0", 1024)
	d21 := newTestDialector("21.0.0.0.0", 1024)
	dEmpty := newTestDialector("", 1024) // 探测失败降级
	// MAX_STRING_SIZE 三态 dialector：STANDARD / EXTENDED / 未探测（Unknown，即 d12）
	d12Std := newTestDialectorWithMaxStringSize("12.1.0.2.0", 1024, MaxStringSizeStandard)
	d12Ext := newTestDialectorWithMaxStringSize("12.1.0.2.0", 1024, MaxStringSizeExtended)
	d12Unknown := d12 // 12c 版本 + 不设 MaxStringSize（零值 Unknown，与 d12 等价）

	tests := []struct {
		name      string
		dialector *Dialector
		mutate    func(*schema.Field)
		want      string
	}{
		// ---- Bool 分支 ----
		{"bool 11g → NUMBER(1)", d11, func(f *schema.Field) { f.DataType = schema.Bool }, "NUMBER(1)"},
		{"bool 12c → NUMBER(1)", d12, func(f *schema.Field) { f.DataType = schema.Bool }, "NUMBER(1)"},
		{"bool 19c → NUMBER(1)", d19, func(f *schema.Field) { f.DataType = schema.Bool }, "NUMBER(1)"},
		{"bool 21c → BOOLEAN", d21, func(f *schema.Field) { f.DataType = schema.Bool }, "BOOLEAN"},
		{"bool 降级 → NUMBER(1)", dEmpty, func(f *schema.Field) { f.DataType = schema.Bool }, "NUMBER(1)"},

		// ---- Int/Uint 分支 ----
		{"int size=0 → SMALLINT", d12, func(f *schema.Field) { f.DataType = schema.Int }, "SMALLINT"},
		{"int size=8 → SMALLINT", d12, func(f *schema.Field) { f.DataType = schema.Int; f.Size = 8 }, "SMALLINT"},
		{"int size=64 → INTEGER", d12, func(f *schema.Field) { f.DataType = schema.Int; f.Size = 64 }, "INTEGER"},
		{"uint size=64 → INTEGER", d12, func(f *schema.Field) { f.DataType = schema.Uint; f.Size = 64 }, "INTEGER"},

		// ---- Int AutoIncrement ----
		{"int autoincrement 11g → INTEGER (no IDENTITY)", d11, func(f *schema.Field) {
			f.DataType = schema.Int
			f.Size = 64
			f.AutoIncrement = true
		}, "INTEGER"},
		{"int autoincrement 12c → INTEGER GENERATED BY DEFAULT AS IDENTITY", d12, func(f *schema.Field) {
			f.DataType = schema.Int
			f.Size = 64
			f.AutoIncrement = true
		}, "INTEGER GENERATED BY DEFAULT AS IDENTITY"},
		{"int autoincrement 19c → INTEGER GENERATED BY DEFAULT AS IDENTITY", d19, func(f *schema.Field) {
			f.DataType = schema.Int
			f.Size = 64
			f.AutoIncrement = true
		}, "INTEGER GENERATED BY DEFAULT AS IDENTITY"},
		{"int autoincrement 21c → INTEGER GENERATED BY DEFAULT AS IDENTITY", d21, func(f *schema.Field) {
			f.DataType = schema.Int
			f.Size = 64
			f.AutoIncrement = true
		}, "INTEGER GENERATED BY DEFAULT AS IDENTITY"},

		// ---- Float 分支 ----
		{"float → FLOAT", d12, func(f *schema.Field) { f.DataType = schema.Float }, "FLOAT"},
		{"float with AUTOINCREMENT → FLOAT GENERATED BY DEFAULT AS IDENTITY", d12, func(f *schema.Field) {
			f.DataType = schema.Float
			f.TagSettings = map[string]string{"AUTOINCREMENT": "true"}
		}, "FLOAT GENERATED BY DEFAULT AS IDENTITY"},

		// ---- String 分支（schema.String / VARCHAR2） ----
		{"string size=100 → VARCHAR2(100)", d12, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 100
		}, "VARCHAR2(100)"},
		{"string size=0 default=1024 → VARCHAR2(1024)", d12, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 0
		}, "VARCHAR2(1024)"},
		{"string size=2000 → VARCHAR2(2000) (12c 32k)", d12, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 2000
		}, "VARCHAR2(2000)"},
		{"string size=4096 12c EXTENDED → VARCHAR2(4096)", d12Ext, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 4096
		}, "VARCHAR2(4096)"},
		{"string size=4096 11g → CLOB", d11, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 4096
		}, "CLOB"},
		{"string size=5000 12c EXTENDED → VARCHAR2(5000)", d12Ext, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 5000
		}, "VARCHAR2(5000)"},
		{"string size=5000 12c STANDARD → CLOB", d12Std, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 5000
		}, "CLOB"},
		{"string size=5000 12c 未探测 → CLOB（保守）", d12Unknown, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 5000
		}, "CLOB"},
		{"string size=5000 11g → CLOB", d11, func(f *schema.Field) {
			f.DataType = schema.String
			f.Size = 5000
		}, "CLOB"},
		{"VARCHAR2(50) → VARCHAR2(50)", d12, func(f *schema.Field) {
			f.DataType = "VARCHAR2"
			f.Size = 50
		}, "VARCHAR2(50)"},

		// ---- Time 分支 ----
		{"time → TIMESTAMP WITH TIME ZONE", d12, func(f *schema.Field) {
			f.DataType = schema.Time
		}, "TIMESTAMP WITH TIME ZONE"},
		{"time precision 6 → TIMESTAMP(6) WITH TIME ZONE", d12, func(f *schema.Field) {
			f.DataType = schema.Time
			f.Precision = 6
		}, "TIMESTAMP(6) WITH TIME ZONE"},

		// ---- Bytes 分支 ----
		{"bytes → BLOB", d12, func(f *schema.Field) { f.DataType = schema.Bytes }, "BLOB"},

		// ---- default 分支：varchar 归一 ----
		{"varchar(1) → VARCHAR2(1)", d12, func(f *schema.Field) { f.DataType = "varchar(1)" }, "VARCHAR2(1)"},
		{"VARCHAR(20) → VARCHAR2(20)", d12, func(f *schema.Field) { f.DataType = "VARCHAR(20)" }, "VARCHAR2(20)"},
		{"varchar2(64) → VARCHAR2(64)", d12, func(f *schema.Field) { f.DataType = "varchar2(64)" }, "VARCHAR2(64)"},
		{"nvarchar2(50) → nvarchar2(50)", d12, func(f *schema.Field) { f.DataType = "nvarchar2(50)" }, "nvarchar2(50)"},
		{"NVARCHAR2(100) → NVARCHAR2(100)", d12, func(f *schema.Field) { f.DataType = "NVARCHAR2(100)" }, "NVARCHAR2(100)"},
		{"text → CLOB", d12, func(f *schema.Field) { f.DataType = "text" }, "CLOB"},
		{"json → CLOB", d12, func(f *schema.Field) { f.DataType = "json" }, "CLOB"},
		{"TEXT uppercase → CLOB", d12, func(f *schema.Field) { f.DataType = "TEXT" }, "CLOB"},
		{"JSON uppercase → CLOB", d12, func(f *schema.Field) { f.DataType = "JSON" }, "CLOB"},

		// ---- varchar 归一：无括号回退 DefaultStringSize ----
		{"varchar → VARCHAR2(1024)", d12, func(f *schema.Field) { f.DataType = "varchar" }, "VARCHAR2(1024)"},

		// ---- bool 23ai → BOOLEAN ----
		{"bool 23ai → BOOLEAN", newTestDialector("23.0.0.0.0", 1024), func(f *schema.Field) { f.DataType = schema.Bool }, "BOOLEAN"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := testField(schema.String) // 默认 string，由 mutate 覆写
			f.TagSettings = map[string]string{}
			tt.mutate(f)
			got := tt.dialector.DataTypeOf(f)
			if got != tt.want {
				t.Errorf("DataTypeOf() = %q, want %q", got, tt.want)
			}
		})
	}
}

// TestExtendedStringLimit 验证 VARCHAR2 大小上限的判定：
// 版本允许（12c+）且探测到 EXTENDED → 32767；其余（11g、未探测、STANDARD）→ 4000
func TestExtendedStringLimit(t *testing.T) {
	tests := []struct {
		name      string
		dialector *Dialector
		want      int
	}{
		{"11g → 4000", newTestDialector("11.2.0.2.0", 1024), 4000},
		{"12c 未探测(Unknown) → 4000", newTestDialector("12.1.0.2.0", 1024), 4000},
		{"12c STANDARD → 4000", newTestDialectorWithMaxStringSize("12.1.0.2.0", 1024, MaxStringSizeStandard), 4000},
		{"12c EXTENDED → 32767", newTestDialectorWithMaxStringSize("12.1.0.2.0", 1024, MaxStringSizeExtended), 32767},
		{"19c EXTENDED → 32767", newTestDialectorWithMaxStringSize("19.0.0.0.0", 1024, MaxStringSizeExtended), 32767},
		{"Config 为 nil → 4000（防御）", &Dialector{Config: nil}, 4000},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.dialector.extendedStringLimit(); got != tt.want {
				t.Errorf("extendedStringLimit() = %d, want %d", got, tt.want)
			}
		})
	}
}

// TestDataTypeOfDoesNotMutateTagSettings 验证 DataTypeOf 不修改字段的 TagSettings map（data race 修复）
func TestDataTypeOfDoesNotMutateTagSettingsV2(t *testing.T) {
	d := newTestDialector("12.1.0.2.0", 1024)
	f := testField(schema.Int)
	f.TagSettings = map[string]string{"RESTRICT": "true", "OTHER": "val"}

	d.DataTypeOf(f)

	if _, ok := f.TagSettings["RESTRICT"]; !ok {
		t.Error("RESTRICT should remain in TagSettings")
	}
	if f.TagSettings["OTHER"] != "val" {
		t.Error("OTHER tag should be unchanged")
	}
}

// TestDefaultValueOfCorrect 重命名版本，确保语义清晰
func TestDefaultValueOfCorrect(t *testing.T) {
	d := newTestDialector("12.1.0.2.0", 1024)
	expr := d.DefaultValueOf(nil)
	e, ok := expr.(clause.Expr)
	if !ok {
		t.Fatalf("expected clause.Expr, got %T", expr)
	}
	if e.SQL != "DEFAULT" {
		t.Errorf("DefaultValueOf().SQL = %q, want %q", e.SQL, "DEFAULT")
	}
}

// TestDataTypeBareType 确认 bareType 转换逻辑（辅助 outParam 测试理解）
func TestDataTypeBareType(t *testing.T) {
	tests := []struct {
		name string
		in   reflect.Type
		want reflect.Type
	}{
		{"int → int64", reflect.TypeFor[int](), reflect.TypeFor[int64]()},
		{"string → string", reflect.TypeFor[string](), reflect.TypeFor[string]()},
		{"bool → bool", reflect.TypeFor[bool](), reflect.TypeFor[bool]()},
		{"float64 → float64", reflect.TypeFor[float64](), reflect.TypeFor[float64]()},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := bareType(tt.in)
			if got != tt.want {
				t.Errorf("bareType(%v) = %v, want %v", tt.in, got, tt.want)
			}
		})
	}
}
